# To change this template, choose Tools | Templates
# and open the template in the editor.
require "sdl"

require "xibe/event"
require "xibe/key"
require "xibe/mouse"
require "xibe/constants"
require "xibe/application"
require "xibe/timer"
require "xibe/color"
require "xibe/layer"
require "xibe/camera"
require "xibe/image"
require "xibe/text"
require "xibe/text_blitter"
require "xibe/mixer"
require "xibe/music"
require "xibe/sample"
require "xibe/sprite"
require "xibe/scene"
require "xibe/tilemap"
